name: Continuous Integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    types: [ opened, synchronize ]

permissions:
  contents: read

jobs:
  build:
  
    runs-on: ubuntu-latest
    env:
      kakao-api-key: ${{secrets.KAKAO_API_KEY}}
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
        
      - name: Build
        run: ./gradlew build --exclude-task test
      
      - name: Test
        run: ./gradlew test -Dkakao.api.key=${{env.kakao-api-key}}
